manifest = "416dbcf35e0cdc43355d9622521f42e361e4b72fe3d4b4aa360f27631d231b0d"

[[dependency]]
package = "github.com/iwatakeshi/to_string"
target = "//:to_string"

[lock."github.com/iwatakeshi/bench"]
versions = [ "branch=master" ]
revision = "2c62e398e552c1a37d066a6d2681f25b65fcfdc5"

[lock."github.com/iwatakeshi/to_string"]
versions = [ "tag=1.0.0-alpha" ]
revision = "c22655357fbe44841c79acf12fd7f60d6d317952"
