manifest = "0e8e6b787476a9a4a869a5d2aeed3fc5e42a1505f4f610e2441c630f77259905"

[[dependency]]
package = "github.com/iwatakeshi/bench"
target = "//:bench"

[[dependency]]
package = "github.com/iwatakeshi/to_string"
target = "//:to_string"

[lock."github.com/iwatakeshi/bench"]
versions = [ "branch=master" ]
revision = "0fe9e1605ee18500fed023ef364abc1cbf322d0a"

[lock."github.com/iwatakeshi/to_string"]
versions = [ "tag=1.0.0-alpha" ]
revision = "b02f78ebbaf245b137e9bb1e4299aced026910a3"
